FROM python:3.8.2-buster

WORKDIR /meeshkan

RUN pip install meeshkan

RUN curl -O https://unpkg.com/@github/openapi@1.3.1/dist/api.github.com.json

EXPOSE 80/tcp

ENTRYPOINT meeshkan mock --port 80 api.github.com.json
